/**
 * Curated icon registry — only the icons actually used in the app.
 * This avoids importing the entire lucide-react library (~3.1MB) at the top level.
 *
 * If you need to add a new icon, add it to this registry.
 * The icon picker (icon-select.tsx) still has access to all icons via a lazy-loaded module.
 */
import {
  User,
  LoaderCircle,
  CirclePlus,
  ChevronDown,
  ChevronUp,
  BrainCog,
  ExternalLink,
  BookOpen,
  LogOut,
  Check,
  Code,
  Plus,
  Trash2,
  AlertTriangle,
  CircleXIcon,
  FileIcon,
  PaperclipIcon,
  EyeIcon,
  EyeOffIcon,
  ArrowLeft,
  ArrowDownIcon,
  PanelRightOpen,
  SquarePen,
  Send,
  FileText,
  MessageSquare,
  NotebookPen,
  X,
  Upload,
  Download,
  Globe,
  ThumbsUpIcon,
  ThumbsDownIcon,
  SendHorizontalIcon,
  CircleHelp,
  EllipsisVertical,
  Pencil,
  CheckIcon,
  CopyIcon,
  Eye,
  EyeOff,
  Plus as PlusIcon,
  CircleX,
  CircleCheck,
  PanelRightClose,
  Languages,
  SlidersVertical,
  SmilePlus,
  MessageCircleCode,
  ScrollText,
  Bug,
  BookA,
  Forward,
  CircleArrowUp,
  Copy,
} from "lucide-react";
import type { ComponentType, SVGProps } from "react";

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

/**
 * Static map of icon name → component.
 * Used by getIcon() for fast lookups without importing the full library.
 */
export const ICON_REGISTRY: Record<string, IconComponent> = {
  User,
  LoaderCircle,
  CirclePlus,
  ChevronDown,
  ChevronUp,
  BrainCog,
  ExternalLink,
  BookOpen,
  LogOut,
  Check,
  Code,
  Plus,
  Trash2,
  AlertTriangle,
  CircleXIcon,
  FileIcon,
  PaperclipIcon,
  EyeIcon,
  EyeOffIcon,
  ArrowLeft,
  ArrowDownIcon,
  PanelRightOpen,
  SquarePen,
  Send,
  FileText,
  MessageSquare,
  NotebookPen,
  X,
  Upload,
  Download,
  Globe,
  ThumbsUpIcon,
  ThumbsDownIcon,
  SendHorizontalIcon,
  CircleHelp,
  EllipsisVertical,
  Pencil,
  CheckIcon,
  CopyIcon,
  Eye,
  EyeOff,
  PlusIcon,
  CircleX,
  CircleCheck,
  PanelRightClose,
  Languages,
  SlidersVertical,
  SmilePlus,
  MessageCircleCode,
  ScrollText,
  Bug,
  BookA,
  Forward,
  CircleArrowUp,
  Copy,
};
